% Clear Everything
clc, clear, close

%Variables
k = 1.380649*10^-23; %Boltzman Constant
Ts = 1; %System Temperature Noise
Bn = 1; %Noise Bandwidth of Receiver

eP = 1; %Permittivity of free space
e0 = 8.854*10^-12; %Farads/m
uP = 1; %Permeability of free space
u0 = 4*pi*10^-7; %Henries/m
sigmaLossTangent = 0; %Loss Tangent (Siemens/m)
waveVelocity = 1/sqrt(u0*e0); % Speed of light mathematically

c = 3*10^8; % Speed of light (m/s)

N = k * Ts * Bn; %Noise Power At Target

Fc = 1;% Frequency of Oscillation (Freq of wave that carries information)
% Frequency of the unmodulated electromagnetic wave
% Once carrier frequency is generated by an oscillator it is modulated with
% information
e = 2.71828; 
f = 1; %Frequency of the wave
w = 2*pi*f; %Angular Frequency of the wave
z = 1; %Position along the direction of wave propagation
E0 = 1; %Amplitude of the electric field, max strength of electric field
% x-direction at any givne point in the z axis
Ex = E0*e^(-j*w*z*sqrt(u0*e0)); %Magnitude of electric field in the 

k0 = w*sqrt(u0*e0); %Free space wave number
Ex = E0*e^(-j*k0*z);
k = w*sqrt(uP*eP);
ExTwoWireTransmission = E0*e*sqrt(-j*k*z);

Zo = 50; %Characteristic Impedance (Ohms)
Zs = 50; %Output port impedence (Ohms)
Zl = 50; %Input ports impedance (Ohms)




% I want to know what is the max range of the radar
% What is the distance of a target
% Plot the target being found
% What is the speed of the target
% What is the direction of the target

%Jackson Requests
%Simulate Radar Signal
%Determine how fast the target is moving
%Determine how far away it is

